Release/login module
wizsolucoes/syz pull request #27
Opened 2021-06-23 21:36 UTC by TamaraMontijo

2021-06-23 23:03 UTC, toureholder requested changes
os assets são necessários?

este componente tá adicionado centenas de arquivos. vamos ter q filtrar só o q é necessário

2021-06-23 23:05 UTC, toureholder commented on packages/ng-syz/projects/ng-syz/src/lib/login-with-carousel-flow/theme/theme.scss
> +// theme.scss
este arquivo é necessário?

2021-06-24 21:06 UTC, toureholder reviewed
packages/ng-syz/projects/ng-syz/src/lib/login-with-carousel-flow/assets/css/fontawesome.css é necessário?

podemos remover a packages/ng-syz/projects/ng-syz/src/lib/login-with-carousel-flow/assets/ ?

2021-06-24 21:06 UTC, toureholder commented on packages/ng-syz/projects/ng-syz/src/lib/login-with-carousel-flow/theme/custom-component-themes.scss
> +// custom-component-themes.scss
este arquivo é necessário?

2021-06-24 21:06 UTC, toureholder commented on packages/ng-syz/projects/ng-syz/src/lib/login-with-carousel-flow/theme/styles.scss
> +@import "./_variables";
estes imports foram feitos em .../projects/ng-syz/src/lib/login-with-carousel-flow/login-with-carousel-flow.component.scss, não?  preicsasmo importar mais de uma vez?

2021-06-24 21:06 UTC, toureholder commented on packages/ng-syz/projects/ng-syz/src/lib/login-with-carousel-flow/theme/styles.scss
> +@font-face {
podemos remover essas regras de font-face para que o componente siga a fonte da aplicação hospedeira?

2021-06-24 21:06 UTC, toureholder commented on packages/ng-syz/package.json
> +    "font-awesome": "^4.7.0",
usamos font-awesome?

2021-06-24 21:15 UTC, toureholder commented on packages/ng-syz/package.json
> +    "font-awesome": "^4.7.0",
se o css de font-awesome está sendo referenciado em packages/ng-syz/projects/app/src/index.html de um CDN precisamos dessa dependência no package.json

2021-06-24 21:16 UTC, toureholder commented on packages/ng-syz/projects/ng-syz/src/lib/login-with-carousel-flow/theme/_grid.scss
> +.linha {
todas essas regras de css são necessárias?

2021-06-24 21:17 UTC, toureholder commented on packages/ng-syz/projects/ng-syz/src/lib/login-with-carousel-flow/theme/_mixins.scss
> +//// App Mixins ////
todas essas regras são necessárias?

2021-06-24 22:32 UTC, TamaraMontijo commented on packages/ng-syz/projects/ng-syz/src/lib/login-with-carousel-flow/login-with-carousel-flow.component.scss
> +          font-size: $font-size-base + 2.75;
Você diz pra ser uma variável de input?

2021-06-30 12:39 UTC, toureholder approved these changes

2021-06-30 13:44 UTC, merged